Repository GSG-G10/AudioGalaxy, pull requests merged in 2021-07, with the labels that each got.

#6 file structure
  .gitignore
  index.html
  package-lock.json
  package.json
  script/apikeys.js
  script/dom.js
  script/fetch.js
  script/logic.js
  script/test.js
  style.css
Labels: Awaiting Review

#8 7 loading page
  images/rocket.svg
  index.html
  style.css
Labels: Awaiting Review

#9 Creat Page Header
  index.html
  style.css
Labels: bug

#10 hide api key - fetch function - change script test value #4
  .gitignore
  index.html
  package.json
  script/apikeys.js
  script/fetch.js
  script/logic.js
Labels: Awaiting Review

#13 nasa api
  .gitignore
  index.html
  script/fetch.js
  script/logic.js
  style.css
Labels: Awaiting Review

#15 Create DOM function and edit logic.js file
  index.html
  script/dom.js
  script/logic.js
Labels: Awaiting Review

#16 edit style to the home page
  index.html
  style.css
Labels: Awaiting Review

#17 Finaly edit to btn up
  index.html
  script/dom.js
  script/logic.js
  style.css
Labels: Awaiting Review

#21 19 loading page
  index.html
  script/dom.js
  script/logic.js
  style.css
Labels: Awaiting Review

#34 Change getTime func to getHours
  script/dom.js
Labels: Done

#37 Abstract return functions
  index.html
  script/dom.js
  script/logic.js
Labels: Awaiting Review
